repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.3.3
    hooks:
    - id: nbqa-black
      args: [--nbqa-mutate]
