repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.6
    hooks:
    - id: nbqa-black
      additional_dependencies: [ black==20.8b1 ]
      args: [--nbqa-mutate ]
    - id: nbqa-isort
      additional_dependencies: [ isort==5.6.4 ]
      args: [ --nbqa-mutate, --profile=black, --project=pandas_profiling ]
    - id: nbqa-pyupgrade
      additional_dependencies: [ pyupgrade==2.7.3 ]
      args: [ --nbqa-mutate, --py36-plus ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
    -   id: pyupgrade
        args: ['--py36-plus','--exit-zero-even-if-changed']
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        files: '.*'
        args: [ --profile=black, --project=pandas_profiling ]
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.46"
    hooks:
    -   id: check-manifest
-   repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
    -   id: flake8
        args: [ "--select=E9,F63,F7,F82"] #,T001
#        additional_dependencies:
#          - flake8-print
