sudo: required
dist: bionic
language: python
cache:
  pip: true
  directories:
    - data/

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - TEST=unit
  - TEST=issue
  - TEST=console
  - TEST=examples
  - TEST=lint
  - TEST=typing

install:
  - pip install --upgrade pip six
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -e .[notebook,app,html]

script:
  - if [ $TEST == 'unit' ]; then pytest --cov=. tests/unit/; fi
  - if [ $TEST == 'issue' ]; then pytest --cov=. tests/issues/; fi
  - if [ $TEST == 'examples' ]; then pytest --cov=. --nbval tests/notebooks/; fi
  - if [ $TEST == 'console' ]; then pandas_profiling -h; fi
  - if [ $TEST == 'typing' ]; then pytest --mypy -m mypy .; fi
  - if [ $TEST == 'lint' ]; then pytest --black -m black src/; flake8 . --select=E9,F63,F7,F82 --show-source --statistics; fi

after_success:
  - codecov -F $TEST
