name: Merge into develop branch



on:
  push:
    branches: 
    - develop



jobs:
  prepare:
    name: Calculate Version and Build Number
    runs-on: ubuntu-20.04

    outputs:
      build_number: ${{ steps.build_number.outputs.value }}
      new_release: ${{ steps.semantic.outputs.new_release_published }}
      release: ${{ steps.semantic.outputs.new_release_version }}
      release_notes: ${{ steps.semantic.outputs.new_release_notes }}
      version: ${{ steps.version.outputs.value }}

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Find Latest Tag
      id: latest_tag
      uses: oprypin/find-latest-tag@v1.1.0
      with:
        repository: ${{ github.repository }}
        regex: '^\d+\.\d+\.\d+'
        releases-only: false

    - name: Extract semantic version
      id: semantic
      run: echo ::set-output name=value::$(echo ${{ steps.latest_tag.outputs.tag }} | sed -r 's|([0-9]+.[0-9]+.[0-9]+).*|\1|g')

    - name: Computed Semantic Version
      run: echo ${{ steps.semantic.outputs.value }}

    - name: Count number or releases for tag
      id: build_number
      run: echo "::set-output name=value::$(($(git tag | grep -c ${{ steps.semantic.outputs.value }}) + 1))"

    - name: Compute version
      id: version
      run: echo "::set-output name=value::${{ steps.semantic.outputs.value }}.pre${{ steps.build_number.outputs.value }}"


  prerelease:
    if: needs.prepare.outputs.new_release == 'true'

    name: Generates Prerelease
    runs-on: ubuntu-20.04

    needs: prepare

    steps:
    - name: Create Pre Release
      uses: actions/create-release@v1
      env:
        BUILD: ${{ needs.prepare.outputs.build_number }}
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        VERSION: ${{ needs.prepare.outputs.release }}
      with:
        tag_name: ${{ env.VERSION }}.${{ env.BUILD }}
        release_name: ${{ needs.prepare.outputs.version }}
        body: ${{ github.event.head_commit.message }}
        prerelease: true


  draft-release:
    if: needs.prepare.outputs.new_release == 'true'

    name: Draft Release
    runs-on: ubuntu-20.04

    needs: prepare

    steps:
    - name: Delete Previous drafts
      uses: hugo19941994/delete-draft-releases@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Create Draft Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: ${{ needs.prepare.outputs.release }}
        release_name: ${{ needs.prepare.outputs.release }}
        body: ${{ needs.prepare.outputs.release_notes }}
        draft: true