name: Release


on:
  release:
    types:
      - released


jobs:
  package:
    name: Build and Package
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
      
    - uses: actions/cache@v1
      name: Cache pip dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
        python -m pip install -r requirements-test.txt
    
    - name: Install
      run: make install

    - name: Lint
      run: make lint
    
    - name:  Build package
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*

    - name: Upload Pipeline Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: dist/

  upload-assets:
    name: Upload Assets to Release
    runs-on: ubuntu-20.04

    needs: package

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: built-artifacts
        path: dist/

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: "dist/*"
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        release-tag: ${{ needs.package.outputs.version }}
  
  publish-pypi:
    name: Publish packages to PyPi
    runs-on: ubuntu-20.04

    needs: package

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: built-artifacts
        path: dist/

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  docs_and_examples:
    name: Documentation and Examples
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Configurating Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local core.autocrlf false

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-test.txt

    - name: Install the package
      run: make install

    - name: Update examples
      run: make examples
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    - name: Build the documentation
      run: make docs

    - name: Create branch name
      run: |
        export BRANCH_NAME="${GITHUB_REF##*/}/"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Move the changes to the gh-pages branch (release branch)
      run: |
        mv docs/ ${{ env.BRANCH_NAME }}
        mkdir docs/
        mv ${{ env.BRANCH_NAME }} docs/${{ env.BRANCH_NAME }}
        mv examples/ ${{ env.BRANCH_NAME }}
        mkdir examples/
        mv ${{ env.BRANCH_NAME }} examples/${{ env.BRANCH_NAME }}
        git add -f docs/${{ env.BRANCH_NAME }}
        git add -f examples/${{ env.BRANCH_NAME }}
        git stash push -- docs/ examples/${{ env.BRANCH_NAME }}
        git fetch origin gh-pages
        git checkout gh-pages
        touch .nojekyll
        git add .nojekyll
        rm -rf docs/${{ env.BRANCH_NAME }}
        rm -rf examples/${{ env.BRANCH_NAME }}
        git add docs/
        git add examples/
        git stash apply
        git commit -m "[skip ci] Updating documentation and examples" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: .
        github_token: ${{ secrets.ACCESS_TOKEN }}
